ARG TOOL_DIR="."

FROM python:3.11-slim

# environment variables
ENV AITHENA_LOG_LEVEL="DEBUG"
ENV EXEC_DIR="/opt/executables"

# Work directory defined in the base container
WORKDIR ${EXEC_DIR}

COPY ${TOOL_DIR} ${EXEC_DIR}/${TOOL_DIR}
COPY common ${EXEC_DIR}/common

# Install the tool
RUN pip3 install ${EXEC_DIR}/${TOOL_DIR}

# Set the entrypoint
ENTRYPOINT ["bash", "-c", "uvicorn polus.aithena.ask_aithena.api.__init__:app --host 0.0.0.0  --port 8000"]
